site_name: Manthan
site_description: Decision Infrastructure for Trusted Systems
site_url: https://pavancharak.github.io/manthan-docs/

theme:
  name: material

  palette:
    scheme: default
    primary: black
    accent: indigo

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - header.autohide
    - content.code.copy
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Investors: investors.md

  - Product:
      - System: system.md
      - PR Gate: pr-gate.md

  - Technology:
      - Architecture: architecture.md
      - Decision Engine: decision-engine.md
      - Contracts: contracts.md

  - Research:
      - Papers: papers.md